### ISSUE TITLE
Nested domains problem

### ISSUE THREAD

**Issue by asaf** [gajus/canonical-reducer-composition-validator#2]
According to the spec, it seems like a reducer such below should work:

``` js
let reducers;

reducers = {
    users: {
        foo: {
            CONSTRUCT: () => {
                return Immutable.List()
            }
        }
    }
}
```

I am getting an error:

```
Reducer definition object action handler names must be valid action names.
```

What's the right syntax for having nested domains ?

**Comment by gajus** [comment]
I apologise. It is a bug. `_.isFunction` was undefined, making the `isDomainMap` malfunction. I have written test cases to ensure this does not happen again. https://github.com/gajus/canonical/tree/1.2.1

**Comment by asaf** [comment]
@gajus Cool, it seems like you are missing unit tests for nested domains (this bug would be discovered as sub domains were never recognized as "domain maps"),

Same goes for the redux-immutable, there are no unit tests for nested domains.

**Comment by gajus** [comment]
Two new tests have been added as a result of this bug:
- https://github.com/gajus/canonical/blob/master/test/isActionMap.js
- https://github.com/gajus/canonical/blob/master/test/isDomainMap.js

These would have caught this issue. @asaf Do you feel there should be a more specific test? Please suggest a description.

Regarding redux-immutable. It is a bit redundant to test the same there since it directly depends on this module.
